[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[build.nixpacksPlan]
rootDirectory = "NUCO"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10